builder:
  track: dev

labels:
  app-group: estafette-controllers
  type: service
  team: estafette-team
  language: golang

version:
  semver:
    major: 1
    minor: 2
    patch: 11
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.2.11

stages:
  build-lint-and-package:
    parallelStages:
      build:
        image: golang:1.18
        env:
          CGO_ENABLED: 0
          GOOS: linux
        commands:
        - go test ./...
        - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

      lint-helm-chart:
        image: extensions/helm:dev
        action: lint

      package-helm-chart:
        image: extensions/helm:dev
        action: package

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  test-helm-chart:
    services:
    - name: kubernetes
      image: bsycorp/kind:latest-1.21
      readiness:
        path: /kubernetes-ready
        port: 10080
    image: extensions/helm:dev
    action: test
    values: |-
      secret:
        cloudflareApiEmail: bot@estafette.io
        cloudflareApiKey: abc
      imagePullSecret:
        registryURL: https://index.docker.io/v1/
        username: estafette.secret(UxxjlP0dfzYMN0B-.aAta8tS2pRYHGdqqfdPBibo8WGzlP9vV8A==.ZRFP9tex-REJAGLZygmunMetFf7EMY-5t6VHX2dcbYPX7odnnB4HlRAQgMq9-_-wF6o6u830OHZIfiozlw==)
        password: estafette.secret(p28YAdrkMJy1gpCC.xv_b7BG-iFpN6Hm644IGdR8tK9EyTVITbG-M2edtzSB1thaaYe8TDupWWneA3Q==.zfjg0jW67V8S6WCSx4RWcEs8PNJVTXEkQWCRxfc59faD9cAyTvqrCpIR9J7CEtMWIg85DjqXU7eA9V9-8Q==)

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: main

  publish-helm-chart:
    image: extensions/helm:dev
    action: publish
    repoBranch: main

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  release:
    stages:
      clone-charts-repo:
        image: extensions/git-clone:dev
        repo: helm-charts
        branch: main

      purge-prerelease-helm-charts:
        image: extensions/helm:dev
        action: purge
        repoBranch: main

      create-github-release:
        image: extensions/github-release:dev
