apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-cloudflare-dns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-cloudflare-dns.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  cloudflareApiEmail: {{.Values.secret.cloudflareApiEmail | toString}}
  cloudflareApiKey: {{.Values.secret.cloudflareApiKey | toString}}
  {{- else }}
  cloudflareApiEmail: {{.Values.secret.cloudflareApiEmail | toString | b64enc}}
  cloudflareApiKey: {{.Values.secret.cloudflareApiKey | toString | b64enc}}
  {{- end }}