apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-cloudflare-dns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-cloudflare-dns.labels" . | indent 4 }}
type: Opaque
data:
  cloudflareApiEmail: {{.Values.secret.cloudflareApiEmail | b64enc}}
  cloudflareApiKey: {{.Values.secret.cloudflareApiKey | b64enc}}